#!/bin/bash

# thai latgv

if [ -x cttex ]
then ./cttex < $1.tex > $1.ttex 
else cttex < $1.tex > $1.ttex
fi
pdflatex $1.ttex
rm -f $1.ttex
if [ -n "$3" ]
then dvips `basename $1` -p $2 -n $3 -o
elif [ -n "$2" ]
then dvips `basename $1` -p $2 -o
elif [ -n "$1" ]
then dvips `basename $1` -o
fi
#gv `basename $1`.ps



